# Generated by Django 4.2.13 on 2024-07-13 22:06

from django.db import migrations, models
import secrets


def generate_unique_order_codes(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        order.order_code = secrets.token_hex(3).upper()[:6]
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_code'),
    ]

    operations = [
        migrations.RunPython(generate_unique_order_codes),
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
