# Generated by Django 4.2.13 on 2024-07-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_available_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
