# Generated by Django 4.2.13 on 2024-07-08 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
