# Generated by Django 4.2.13 on 2024-07-13 23:39

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20240713_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_code',
            field=models.CharField(default=orders.models.generate_order_code, max_length=6, unique=True),
        ),
    ]
